version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: url-shortener_postgres
    environment:
      POSTGRES_DB: shortener_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 8246
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data_url

volumes:
  pgdata:
