version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: todoapp_postgres
    environment:
      POSTGRES_DB: sso_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 8246
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
